GET http://localhost:5000/v1/profile
###

GET http://localhost:5000/v1/data
###

GET http://localhost:5000/v1/profile/2
###

POST http://localhost:5000/v1/profile
Content-Type : application/json

{
    "name": "Latif ismail ajide",
    "initials": "Latif",
    "url" : "https://latifismailadjie.com",
    "location" : "Jakarta Barat",
    "locationLink" : "",
    "description" : "Tester",
    "summary" : "tester",
    "avatarUrl" :"tester"
}
###

PATCH  http://localhost:5000/v1/profile/2
Content-Type : application/json

{
    "name": "Latif ismail",
    "initials": "Latif",
    "url" : "https://latifismailadjie.com",
    "location" : "Jakarta Barat",
    "locationLink" : "https://www.google.com/maps",
    "description" : "Fullstack developer. Saya suka membangun sesuatu dan membantu orang lain.",
    "summary" : "Pada awal karir saya, saya mendalami pengembangan web dengan spesialisasi dalam PHP dan framework seperti CodeIgniter dan Laravel. Setelah menyelesaikan puluhan proyek web dan satu aplikasi mobile berbasis Java, saya memutuskan untuk mengembangkan karir saya secara mandiri. Saya antusias terhadap teknologi, selalu belajar hal baru, dan tidak ragu mendalami topik kompleks. Saya percaya pada inovasi dan terus mencari cara untuk menciptakan solusi yang efektif dalam setiap proyek yang saya kerjakan.",
    "avatarUrl" :"/me.jpg"
}

###
DELETE http://localhost:5000/v1/profile/1

### SKILLS
GET http://localhost:5000/v1/skills


###
DELETE http://localhost:5000/v1/skills/5

###
POST http://localhost:5000/v1/skills
Content-Type: application/json

{
    "name" : "Tester"
}

###
PATCH http://localhost:5000/v1/skills/1
Content-Type: application/json

{
    "name" : "Express JS"
}
